# Dockerfile to create a base image for Jetson ARM64 devices
FROM ubuntu:22.04 AS base


FROM --platform=arm64 base AS dev

RUN apt-key adv --fetch-key https://repo.download.nvidia.com/jetson/jetson-ota-public.asc \
  & cat "deb http://repo.download.nvidia.com/jetson/x86_64/jammy r36.3 main" > /etc/apt/sources.list.d/nvidia-l4t-jetson.list \
    & apt-get -y update \
    & apt-get -y install nvidia-cuda-dev
